---
- name: Set Specific Ownership for /mnt and Yugabyte Directories
  hosts: localhost
  become: yes

  tasks:
    ## 1. Set Ownership for /mnt
    - name: Set /mnt ownership to ybaadmin:ybaadmin
      ansible.builtin.file:
        path: /mnt
        owner: ybaadmin
        group: ybaadmin
        state: directory
        # mode: '0755' # You can optionally set mode here if needed
      # Add a handler to skip this if user/group doesn't exist
      ignore_errors: true

    ## 2. Set Ownership for Yugabyte Directories
    - name: Set Yugabyte data directories ownership to yugabyte:yugabyte recursively
      ansible.builtin.file:
        path: "/mnt/{{ item }}"
        owner: yugabyte
        group: yugabyte
        state: directory
        recurse: yes
      loop:
        - yba-wal
        - yba-shared
        - yba-data
      # Add a handler to skip this if user/group doesn't exist
      ignore_errors: true