---
- name: Setup WAL, Shared, and Data disks
  hosts: localhost
  become: yes

  vars:
    disks:
      - { device: "/dev/sdb", part: "/dev/sdb1", mount: "/mnt/yba-wal" }
      - { device: "/dev/sdc", part: "/dev/sdc1", mount: "/mnt/yba-shared" }
      - { device: "/dev/sdd", part: "/dev/sdd1", mount: "/mnt/yba-data" }

  tasks:

    - name: Create GPT partition table
      ansible.builtin.command: "parted -s {{ item.device }} mklabel gpt"
      loop: "{{ disks }}"
      failed_when: false

    - name: Create primary ext4 partition
      ansible.builtin.command: "parted -s {{ item.device }} mkpart primary ext4 0% 100%"
      loop: "{{ disks }}"
      failed_when: false

    - name: Create ext4 filesystem (only if missing)
      ansible.builtin.command: "mkfs.ext4 {{ item.part }}"
      when: "'ext4' not in lookup('ansible.builtin.pipe', 'blkid -o value -s TYPE ' ~ item.part)"
      loop: "{{ disks }}"

    - name: Ensure mount directory exists
      ansible.builtin.file:
        path: "{{ item.mount }}"
        state: directory
        mode: '0755'
      loop: "{{ disks }}"

    - name: Get UUID of each partition
      ansible.builtin.command: "blkid -s UUID -o value {{ item.part }}"
      register: uuid_output
      loop: "{{ disks }}"
      loop_control:
        label: "{{ item.part }}"

    # ------------------------------
    # FIX #1: Combine UUID with disk info
    # ------------------------------
    - name: Build list of disks with UUID
      set_fact:
        disks_with_uuid: "{{ disks_with_uuid | default([]) + [ item.0 | combine({'uuid': item.1.stdout }) ] }}"
      loop: "{{ disks | zip(uuid_output.results) }}"
      loop_control:
        label: "{{ item.0.part }}"

    # ------------------------------
    # FIX #2: Use item.uuid (no more loop.index0)
    # ------------------------------
    - name: Add fstab entry for each mounted volume
      ansible.builtin.lineinfile:
        path: /etc/fstab
        line: "UUID={{ item.uuid }} {{ item.mount }} ext4 defaults 0 0"
        regexp: "{{ item.mount | regex_escape() }}"
        state: present
      loop: "{{ disks_with_uuid }}"

    - name: Mount all drives
      ansible.builtin.command: "mount -a"
      changed_when: false
