---
- name: Mount YBA disks (Ansible 2.14 compatible)
  hosts: localhost
  become: yes

  vars:
    disks:
      - device: "/dev/sdb"
        mount_point: "/mnt/shared"
        fs_type: "ext4"

      - device: "/dev/sdc"
        mount_point: "/mnt/wal1"
        fs_type: "ext4"

      - device: "/dev/sdd"
        mount_point: "/mnt/data1"
        fs_type: "ext4"

  tasks:

    - name: Ensure mount directories exist
      file:
        path: "{{ item.mount_point }}"
        state: directory
        mode: '0755'
      loop: "{{ disks }}"

    - name: Create filesystem if missing
      filesystem:
        fstype: "{{ item.fs_type }}"
        dev: "{{ item.device }}"
      loop: "{{ disks }}"

    - name: Get UUIDs after filesystem creation
      command: "blkid -s UUID -o value {{ item.device }}"
      loop: "{{ disks }}"
      register: uuid_results
      changed_when: false

    - name: Add fstab entries
      lineinfile:
        path: /etc/fstab
        line: "UUID={{ uuid_results.results[item_index].stdout }} {{ item.mount_point }} {{ item.fs_type }} defaults 0 0"
        state: present
      loop: "{{ disks }}"
      loop_control:
        index_var: item_index

    - name: Mount all from fstab
      command: mount -a
