---
- name: Generate RSA SSH Key for ybaadmin
  hosts: localhost
  become: yes
  become_user: ybaadmin

  tasks:
    - name: Check if private key already exists
      stat:
        path: /home/ybaadmin/.ssh/id_rsa
      register: key_stat
      changed_when: false

    - name: Generate new RSA key (4096-bit, PEM format)
      ansible.builtin.command: "ssh-keygen -t rsa -b 4096 -m PEM -f /home/ybaadmin/.ssh/id_rsa -N \"\""
      args:
        # Prevent the task from running if the key already exists
        creates: /home/ybaadmin/.ssh/id_rsa
      when: not key_stat.stat.exists
      
    - name: Ensure correct permissions on .ssh directory
      ansible.builtin.file:
        path: /home/ybaadmin/.ssh
        state: directory
        mode: '0700'
        owner: ybaadmin
        group: ybaadmin
        
    - name: Ensure correct permissions on private key
      ansible.builtin.file:
        path: /home/ybaadmin/.ssh/id_rsa
        mode: '0600'
        owner: ybaadmin
        group: ybaadmin