---
- name: Install YBA via yba-ctl using Ansible
  hosts: localhost
  become: true

  vars:
    yba_dir: "/home/ybaadmin/yba_installer_full-2024.2.5.1-b1"
    yba_opt_dir: "/opt/yba-ctl"
    license_src: "/opt/yba-ctl/yba.lic"
    skip_preflight: "disk-availability,memory,cpu"

  tasks:
    # ---------------------------------------------------------
    # STEP 0: Backup License Before Clean
    # ---------------------------------------------------------
    - name: Ensure license file exists
      stat:
        path: "{{ license_src }}"
      register: lic_check

    - fail:
        msg: "License file not found at {{ license_src }}"
      when: not lic_check.stat.exists

    - name: Copy license to /tmp before clean
      copy:
        src: "{{ license_src }}"
        dest: "/tmp/yba.lic"
        mode: '0644'

    # ---------------------------------------------------------
    # STEP 1: CLEAN
    # ---------------------------------------------------------
    - name: Run yba-ctl clean
      command: ./yba-ctl clean --all --force
      args:
        chdir: "{{ yba_dir }}"
      register: clean_output
      failed_when: false

    - debug:
        var: clean_output.stdout

    # ---------------------------------------------------------
    # STEP 2: Restore License After Clean
    # ---------------------------------------------------------
    - name: Ensure /opt/yba-ctl directory exists
      file:
        path: "{{ yba_opt_dir }}"
        state: directory
        mode: '0755'

    - name: Copy license back to /opt/yba-ctl/
      copy:
        src: "/tmp/yba.lic"
        dest: "{{ yba_opt_dir }}/yba.lic"
        owner: ybaadmin
        group: ybaadmin
        mode: '0644'

    # ---------------------------------------------------------
    # STEP 3: PREFLIGHT
    # ---------------------------------------------------------
    - name: Run yba-ctl preflight
      command: >
        ./yba-ctl --skip_preflight {{ skip_preflight }}
        preflight --force
      args:
        chdir: "{{ yba_dir }}"
      register: preflight_output

    - debug:
        var: preflight_output.stdout


  
    # ---------------------------------------------------------
    # STEP 2.5: Update installRoot
    # ---------------------------------------------------------
    - name: Update installRoot in yba-ctl.yml
      ansible.builtin.replace:
        path: /opt/yba-ctl/yba-ctl.yml
        regexp: '^installRoot:.*'
        replace: 'installRoot: "/mnt/yba"'

    - name: Verify updated installRoot
      shell: "grep '^installRoot' /opt/yba-ctl/yba-ctl.yml"
      register: installroot_verify
      changed_when: false

    - debug:
        msg: "{{ installroot_verify.stdout }}"


    # ---------------------------------------------------------
    # STEP 4: INSTALL
    # ---------------------------------------------------------
    - name: Run yba-ctl install
      command: >
        ./yba-ctl --skip_preflight {{ skip_preflight }}
        install --force
      args:
        chdir: "{{ yba_dir }}"
      register: install_output

    - debug:
        var: install_output.stdout
