---
- name: Configure SSH for Pubkey Auth and Enable NOPASSWD Sudo
  hosts: localhost
  become: yes
  
  tasks:

    ## --- SSH Daemon Configuration (/etc/ssh/sshd_config) ---

    - name: Ensure PublickeyAuthentication is explicitly set to 'yes'
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PubkeyAuthentication\s+' # Finds commented or uncommented line
        line: "PubkeyAuthentication yes"
        validate: '/usr/sbin/sshd -t -f %s'
        state: present
        
    - name: Ensure PasswordAuthentication is explicitly set to 'no' (optional, but good security practice)
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^#?PasswordAuthentication\s+' 
        line: "PasswordAuthentication no"
        validate: '/usr/sbin/sshd -t -f %s'
        state: present

    - name: Restart sshd service to apply new configuration
      ansible.builtin.service:
        name: sshd
        state: restarted

    ## --- Sudoers Configuration (/etc/sudoers) ---

    - name: Allow 'wheel' group to use sudo without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: '%wheel        ALL=(ALL)       NOPASSWD: ALL'
        regexp: '^%wheel\s+'
        validate: '/usr/sbin/visudo -cf %s' # Ensures syntax is valid
    
    - name: Allow 'ybaadmin' user to use sudo without password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        state: present
        line: 'ybaadmin      ALL=(ALL)       NOPASSWD: ALL'
        regexp: '^ybaadmin\s+'
        validate: '/usr/sbin/visudo -cf %s' # Ensures syntax is valid